server:
  port: 8989

management:
  port: 8990

spring:
  application:
    name: turbine

logging:
  level:
    org.springframework.cloud: 'INFO'

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

turbine:
  app-config: message-sender,message-receiver
  cluster-name-expression: "'default'"
  combine-host-port: true