server:
  port: 8888

#eureka:
#  client:
#    healthcheck:
#      enabled: true
#    serviceUrl:
#      defaultZone: http://192.168.31.80:8761/eureka/,http://192.168.31.80:8762/eureka/
#  instance:
#    lease-expiration-duration-in-seconds: 30
#    lease-renewal-interval-in-seconds: 10

security:
  user:
    name: dumars
    password: p@ssw0rd