server:
  port: 8081

spring:
  application:
    name: message-receiver

logging:
    level:
      org.springframework.web: WARN

management:
#  port: 9000
  security:
    enabled: true
  context-path: /admin
