
---
spring:
  application:
    name: eureka
  profiles: peer1
server:
  port: 8761
  host: localhost
eureka:
  instance:
    hostname: peer1
    preferIpAddress: false
    instanceId: ${spring.cloud.client.ipAddress}:${server.port}
#    statusPageUrlPath: ${management.context-path}/info
#    healthCheckUrlPath: ${management.context-path}/health
    leaseRenewalIntervalInSeconds: 5
  server:
    eviction-interval-timer-in-ms: 4000
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://192.168.31.80:8762/eureka/

---
spring:
  application:
    name: eureka
  profiles: peer2
server:
  port: 8762
  host: localhost
eureka:
  instance:
    hostname: peer2
    preferIpAddress: false
    instanceId: ${spring.cloud.client.ipAddress}:${server.port}
#    statusPageUrlPath: ${management.context-path}/info
#    healthCheckUrlPath: ${management.context-path}/health
    leaseRenewalIntervalInSeconds: 5
  server:
    eviction-interval-timer-in-ms: 4000
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://192.168.31.80:8761/eureka/
