server:
  port: 8080

spring:
  application:
    name: message-sender

logging:
    level:
      org.springframework.ws: DEBUG

feign:
  hystrix:
    enabled: true

#security:
#  user:
#    name: dumars
#    password: p@ssw0rd
#    role: ADMIN

management:
#  port: 9000
  security:
    enabled: true
  context-path: /admin

endpoints:
  health:
    sensitive: true
